// packages/vue2/src/LyEditor.vue
<template>
  <div
    data-testid="ly-editor-root"
    data-ly-editor="true"
    :data-locale="locale"
    :data-has-messages="messages ? '1' : '0'"
  ></div>
</template>

<script>
export default {
  name: 'LyEditor',
  props: {
    locale: {
      type: String,
      default: 'zh-CN'
    },
    messages: {
      type: Object,
      default: undefined
    }
  }
}
</script>

// packages/react/src/LyEditor.tsx
import React from 'react'

export interface LyEditorProps {
  locale?: string
  messages?: Record<string, Record<string, string>>
}

export interface LyEditorRef {
  getEditor: () => unknown
  exec: (command?: string, payload?: unknown) => void
  getValue: () => unknown[]
  setValue: (next?: unknown[]) => void
  destroy: () => void
}

export function LyEditor(props: LyEditorProps) {
  return React.createElement('div', {
    'data-testid': 'ly-editor-root',
    'data-ly-editor': true,
    'data-locale': props.locale ?? 'zh-CN',
    'data-has-messages': props.messages ? '1' : '0'
  })
}
